### ISSUE TITLE
How Hide Column and Filter?

### ISSUE THREAD

**Issue by DottorCry** [evrencoskun/TableView#103]
Thanks you all, I am a neophyte to develop in android and use this object. 

I have a Json result to show in tableview with a specific layout define in other Json. 
I show the result in correct tableview but I can't hide columns that I use to filter. 
I have 5 columns that I use to filter and  with this code I filter correctly data:
**mainFragment.filterTable(5, spSettore.getSelectedItem().toString());**
**mTableFilter.set(col, filter);**

I try to hide the column with this code
**mTableView.hideColumn(0);**

but this is my error
Process: com.bip.icade, PID: 3073
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.evrencoskun.tableview.TableView.hideColumn(int)' on a null object reference at com.bip.icade.fragment.DetailCatalogFragment.HideCol(DetailCatalogFragment.java:232) at com.bip.icade.activity.DetailCatalogActivity.HideColumn(DetailCatalogActivity.java:610).

Idea? 
Is possibile to hide columns that i use to filter?

**Comment by sonique6784** [comment]
@DottorCry ,
the TableView is not set when you try to access it. Please follow the README, has your project is not setup properly.

**Comment by DottorCry** [comment]
Sorry but I think that table is correctly set. 
Steps are:

**1. DetailCatalogActivity: Load Fragment**
getSupportFragmentManager().beginTransaction().add(R.id.activity_container, mainFragment, DetailCatalogFragment.class.getSimpleName()).commit();

**2. OnCreateView DetailCatalogFragment:**
  public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle
            savedInstanceState) {
        Log.i(getString(R.string.tag_log), "DETAIL CATALOG Load data into Table");
        View view = inflater.inflate(R.layout.fragment_detail_catalog, container, false);
        TableView fragment_container = view.findViewById(R.id.tab_detailCatalog);
        mTableView = createTableView();
        mTableFilter = new Filter(mTableView);
        fragment_container.addView(mTableView);
        loadData();
        return view;
    }

**3. DetailCatalogFragment: Specific createTable**
  private TableView createTableView() {
        TableView tableView = new TableView(getContext());
        mTableAdapter = new DetailCatalogAdapter(getContext());
        tableView.setAdapter(mTableAdapter);
        tableView.setTableViewListener(new TableViewListener(tableView));
        return tableView;
    }

**4. DetailCatalogFragment: Load data**
    private void loadData() {
        mColumnHeaderList = createColumnHeader();
        mCellList = loadCellModelList();
        mRowHeaderList = createRowHeaderList();
        mTableAdapter.setAllItems(mColumnHeaderList, mRowHeaderList, mCellList);
    }

**5. DetailCatalogFragment: Specific function**
    public void HideCol(int col) {
       mTableView.hideColumn(0);
    }

When use HideColumn function? 
Thanks

**Comment by evrencoskun** [comment]
Hi @DottorCry ,

`java.lang.NullPointerException: Attempt to invoke virtual method 'void com.evrencoskun.tableview.TableView.hideColumn(int)' on a null object reference at com.bip.icade.fragment.DetailCatalogFragment.HideCol(DetailCatalogFragment.java:232) at com.bip.icade.activity.DetailCatalogActivity.HideColumn(DetailCatalogActivity.java:610).`
According to your error, your tableView instance is null at that time. Please check your fragment code.

For example; you may change below code. Because, even if you create your tableView in createTableView function, you cast the view whose id is R.id.tab_detailCatalog as a TableView. 
  
`TableView fragment_container = view.findViewById(R.id.tab_detailCatalog);
`

**Comment by DottorCry** [comment]
I read the error but i don't understand when I use the HideColumn function.

how should I change this code TableView fragment_container = view.findViewById(R.id.tab_detailCatalog);?
fragment_container is my table:

    <com.evrencoskun.tableview.TableView
        android:id="@+id/tab_detailCatalog"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:column_header_height="@dimen/table_view_cell_height"
        app:row_header_width="@dimen/table_view_row_header_width"
        app:selected_color="@color/selected_background_color"
        app:separator_color="@color/separator_color"
        app:shadow_color="@color/shadow_background_color" />

Thanks

**Comment by evrencoskun** [comment]
According to the below code, you create multiple TableView.

```java

private TableView mTableView;

public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle
            savedInstanceState) {
        Log.i(getString(R.string.tag_log), "DETAIL CATALOG Load data into Table");
        View view = inflater.inflate(R.layout.fragment_detail_catalog, container, false);
        // First tableView created from xml side.
        mTableView= view.findViewById(R.id.tab_detailCatalog);
         // However, you also create another tableView in the below line.
        //createTableView();
        // just initalize the tableView instead of new one.
        initilazeTableView();

        fragment_container.addView(mTableView);
        loadData();
        return view;
    }

private void initilazeTableView() {
        // You don't need to create a new TableView
        //TableView tableView = new TableView(getContext());
        
        mTableAdapter = new DetailCatalogAdapter(getContext());
        mTableView.setAdapter(mTableAdapter);
        mTableView.setTableViewListener(new TableViewListener(mTableView));

        mTableFilter = new Filter(mTableView);
}
```

**Comment by DottorCry** [comment]
OK thanks. 
I have modify my code in according to your suggest.

When can I hide the column?
I try to call the function but result is the same.

FATAL EXCEPTION: main
Process: com.bip.icade, PID: 7433
java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.widget.RecyclerView$Adapter com.evrencoskun.tableview.adapter.recyclerview.CellRecyclerView.getAdapter()' on a null object reference

Can you help me?
Thanks

**Comment by MagoMtz** [comment]
Hi DottorCry, did you solve your isue? I'm stuck in the same problem
