### ISSUE TITLE
java.lang.IndexOutOfBoundsException when sorting column

### ISSUE THREAD

**Issue by marconealberto** [evrencoskun/TableView#109]
I tried to copy the sample app as much as I could, but I'm probably missing something.

```
Whenever I call the tableView.sortColumn with the right parameters (copied and pasted from the sample), I get the error:

W/System.err: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
W/System.err:     at java.util.ArrayList.get(ArrayList.java:411)
W/System.err:     at com.evrencoskun.tableview.sort.ColumnSortComparator.compare(ColumnSortComparator.java:39)
                  at com.evrencoskun.tableview.sort.ColumnSortComparator.compare(ColumnSortComparator.java:28)
                  at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
                  at java.util.TimSort.sort(TimSort.java:234)
W/System.err:     at java.util.Arrays.sort(Arrays.java:1523)
                  at java.util.Collections.sort(Collections.java:238)
                  at com.evrencoskun.tableview.handler.ColumnSortHandler.sort(ColumnSortHandler.java:110)
                  at com.evrencoskun.tableview.TableView.sortColumn(TableView.java:430)
```

where should I be looking for?
what array is sized 0?

**Comment by marconealberto** [comment]
sorry, my error!
