### ISSUE TITLE
setSelectedRow inside onCellClicked causes NPE

### ISSUE THREAD

**Issue by marconealberto** [evrencoskun/TableView#110]
I want to change the behavior of the tableview, when an user clicks on the cell I want it to select the whole row.
I tried to put the select here:

```
@Override
	public void onCellClicked(@NonNull RecyclerView.ViewHolder cellView, int column, int row) {
		// Do what you want.
		mTableView.setSelectedRow(row);
	}
```
(not sure if this is the right way of doing it)

and I get the NPE

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.evrencoskun.tableview.adapter.recyclerview.holder.AbstractViewHolder.setBackgroundColor(int)' on a null object reference
                      at com.evrencoskun.tableview.handler.SelectionHandler.setPreviousSelectedView(SelectionHandler.java:124)
                      at com.evrencoskun.tableview.handler.SelectionHandler.setSelectedRowPosition(SelectionHandler.java:86)
```

because apparently 

```
 AbstractViewHolder rowViewHolder = (AbstractViewHolder) getRowHeaderRecyclerView()
                .findViewHolderForAdapterPosition(row);
```

returns null.

**Comment by evrencoskun** [comment]
Hi @marconealberto 

There is something wrong with your code. Because I've just tested and I works well in the sample app.

**Comment by dmitrychaban** [comment]
Same problem. Any updates on this?
Apparently It firstly selects current cell and after that we select whole row

**Comment by DavideBicego** [comment]
@marconealberto This was happening to me too because I wasn't setting row headers (cause I didn't want them). Just hide them by setting row headers width to 0

**Comment by fgustovo** [comment]
i already use row headers but crash is happening to me too.

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'android.support.v7.widget.RecyclerView$ViewHolder com.evrencoskun.tableview.adapter.recyclerview.CellRecyclerView.findViewHolderForAdapterPosition(int)' on a null object reference
com.evrencoskun.tableview.handler.SelectionHandler.changeVisibleCellViewsBackgroundForColumn (SelectionHandler.java:342)
```

**Comment by dmitrychaban** [comment]
I also had this issue few month ago, the problem was that some of latest cells haven't been drawn on screen e.g 1th 2th and 3th columns have been drawn but 4th were out of screen. As a result, adapter couldn't find this view.
Maybe this would help somehow

**Comment by fgustovo** [comment]
Yes columns 4 to 8 is out of screen. but i cant remove this columns. 
@evrencoskun can you fix the problem with @dmitrychaban 's description?

**Comment by dmitrychaban** [comment]
@fgustovo please check `onCreateColumnHeaderViewHolder()` and `onCreateRowHeaderViewHolder()` in adapter, if they return correct views . Also, I'm setting `
        app:column_header_height="48dp"` and `app:row_header_width="0dp"`(I don't want to show row headers), maybe you haven't put them or they're not correct.
If this won't work, please put your code here, I'll try to help :)

**Comment by fgustovo** [comment]
thanks @dmitrychaban. 

Its hard to share all related codes but i believe i use it correctly:)
the crash is thrown rarely. Its about 15 times per 10K daily active user.
