### ISSUE TITLE
'com.evrencoskun.tableview.adapter.recyclerview.CellRecyclerView.getScrolledX()' on a null object reference

### ISSUE THREAD

**Issue by himangipatel** [evrencoskun/TableView#134]
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.evrencoskun.tableview.adapter.recyclerview.CellRecyclerView.getScrolledX()' on a null object reference
        at com.evrencoskun.tableview.layoutmanager.CellLayoutManager.fitSize2(CellLayoutManager.java:288)
        at com.evrencoskun.tableview.layoutmanager.CellLayoutManager.fitWidthSize2(CellLayoutManager.java:265)
        at com.evrencoskun.tableview.layoutmanager.CellLayoutManager.measureChildWithMargins(CellLayoutManager.java:415)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1585)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3225)
        at android.view.View.measure(View.java:21040)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)

**Comment by evrencoskun** [comment]
Hi @himangipatel 

Could you please explain the case that makes this error?
