### ISSUE TITLE
App stops when orientation changed

### ISSUE THREAD

**Issue by joegillian** [evrencoskun/TableView#145]
App runs normally in both vertical and horizontal mode. But when phone's orientation changed app stops ands gives the error below. Downloaded library and tried this without changing anything and the same error appeared.

![dik](https://user-images.githubusercontent.com/37173926/43246889-c06ea84c-90bb-11e8-8ea4-9545a3143995.PNG)
![yatay](https://user-images.githubusercontent.com/37173926/43246893-c4493b80-90bb-11e8-9b51-e123fed2fe42.PNG)

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.evrencoskun.tableviewsample, PID: 9795
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.evrencoskun.tableviewsample/com.evrencoskun.tableviewsample.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.evrencoskun.tableview.filter.Filter.set(java.lang.String)' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4699)
                      at android.app.ActivityThread.-wrap18(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.evrencoskun.tableview.filter.Filter.set(java.lang.String)' on a null object reference
                      at com.evrencoskun.tableviewsample.MainFragment.filterTable(MainFragment.java:160)
                      at com.evrencoskun.tableviewsample.MainFragment$3.onTextChanged(MainFragment.java:255)
                      at android.widget.TextView.sendOnTextChanged(TextView.java:9364)
                      at android.widget.TextView.setText(TextView.java:5397)
                      at android.widget.TextView.setText(TextView.java:5250)
                      at android.widget.EditText.setText(EditText.java:113)
                      at android.widget.TextView.setText(TextView.java:5207)
                      at android.widget.TextView.onRestoreInstanceState(TextView.java:5082)
                      at android.view.View.dispatchRestoreInstanceState(View.java:17706)
                      at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
                      at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
                      at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3751)
                      at android.view.View.restoreHierarchyState(View.java:17684)
                      at android.support.v4.app.Fragment.restoreViewState(Fragment.java:396)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1445)
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                      at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
                      at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
                      at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
                      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
                      at android.app.Activity.performStart(Activity.java:7029)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4699) 
                      at android.app.ActivityThread.-wrap18(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595) 
                      at android.os.Handler.dispatchMessage(Handler.java:106) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6494) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by joegillian** [comment]
Found the solution. Adding  android:configChanges="orientation|screenSize" line to activity in manifest file resolves the problem.
