### ISSUE TITLE
java.lang.StackOverflowError: stack size 8MB - FAILED BINDER TRANSACTION

### ISSUE THREAD

**Issue by tuvirus** [evrencoskun/TableView#148]
Hello, @evrencoskun 

I have an issue with the table, currently i'm loading aprox. 150 rows in the table from DB. The issue is that when i slide on the table is ok, but when i slide my navigation view and back to the activity suddenly it crashes.

I was using version 0.8.8 of TableView and now i usde 0.8.7 but the problem persists.

Here is what i get from Logcat.

08-08 17:51:28.271 5386-5386/com.gigex.fitosoft.analizador D/Error: ERR: exClass=java.lang.StackOverflowError
08-08 17:51:28.271 5386-5386/com.gigex.fitosoft.analizador D/Error: ERR: exMsg=stack size 8MB
08-08 17:51:28.271 5386-5386/com.gigex.fitosoft.analizador D/Error: ERR: file=ChildHelper.java
08-08 17:51:28.271 5386-5386/com.gigex.fitosoft.analizador D/Error: ERR: class=android.support.v7.widget.ChildHelper
08-08 17:51:28.271 5386-5386/com.gigex.fitosoft.analizador D/Error: ERR: method=getChildCount line=253
08-08 17:51:28.286 5386-5386/com.gigex.fitosoft.analizador D/Error: ERR: stack=java.lang.StackOverflowError: stack size 8MB
                                                                        at android.support.v7.widget.ChildHelper.getChildCount(ChildHelper.java:253)
                                                                        at android.support.v7.widget.RecyclerView$LayoutManager.getChildCount(RecyclerView.java:8350)
                                                                        at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1323)
                                                                        at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1076)
                                                                        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1790)
                                                                        at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1697)
                                                                        at com.evrencoskun.tableview.layoutmanager.CellLayoutManager.scrollVerticallyBy(CellLayoutManager.java:95)
                                                                        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1790)
                                                                        at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1697)
                                                                        at com.evrencoskun.tableview.listener.scroll.VerticalRecyclerViewListener.onScrolled(VerticalRecyclerViewListener.java:120)
                                                                        at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4748)
                                                                        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1819)
                                                                        at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1697)
                                                                        at com.evrencoskun.tableview.layoutmanager.CellLayoutManager.scrollVerticallyBy(CellLayoutManager.java:95)
                                                                        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1790)
                                                                        at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1697)
                                                                        at com.evrencoskun.tableview.listener.scroll.VerticalRecyclerViewListener.onScrolled(VerticalRecyclerViewListener.java:120)
                                                                        at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4748)
                                                                        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1819)
                                                                        at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1697)
                                                                        at com.evrencoskun.tableview.layoutmanager.CellLayoutManager.scrollVerticallyBy(CellLayoutManager.java:95)
                                                                        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1790)
                                                                        at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1697)
                                                                        at com.evrencoskun.tableview.listener.scroll.VerticalRecyclerViewListener.onScrolled(VerticalRecyclerViewListener.java:120)
                                                                        at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4748)
                                                                        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1819)
                                                                        at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1697)
                                                                        at com.evrencoskun.tableview.layoutmanager.CellLayoutManager.scrollVerticallyBy(CellLayoutManager.java:95)
                                                                        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1790)
                                                                        at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1697)
                                                                        at com.evrencoskun.tableview.listener.scroll.VerticalRecyclerViewListener.onScrolled(VerticalRecyclerViewListener.java:120)
                                                                        at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4748)
                                                                        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1819)
                                                                        at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1697)
                                                                        at com.evrencoskun.tableview.layoutmanager.CellLayoutManager.scrollVerticallyBy(CellLayoutManager.java:95)
                                                                        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1790)
                                                                        at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1697)
                                                                        at com.evrencoskun.tableview.listener.scroll.VerticalRecyclerViewListener.onScrolled(VerticalRecyclerViewListener.java:120)
                                                                        at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4748)
                                                                        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1819)
                                                                        at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1697)
                                                                        at com.evrencoskun.tableview.layoutmanager.CellLayoutManager.scrollVerticallyBy(CellLayoutManager.java:95)
                                                                        at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1790)
                                                                        at android.support.v7.widget.RecyclerView.scrollBy(RecyclerView.java:1697)
                                                                    	at com.evrencoskun.tablev
08-08 17:51:28.286 5386-5386/com.gigex.fitosoft.analizador D/Error: ERR: TOTAL BYTES WRITTEN: 1363188
08-08 17:51:28.286 5386-5386/com.gigex.fitosoft.analizador E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1363272)
08-08 17:51:28.290 5386-5386/com.gigex.fitosoft.analizador E/AndroidRuntime: Error reporting crash
                                                                             android.os.TransactionTooLargeException: data parcel size 1363272 bytes
                                                                                 at android.os.BinderProxy.transactNative(Native Method)
                                                                                 at android.os.BinderProxy.transact(Binder.java:503)
                                                                                 at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4471)
                                                                                 at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
                                                                                 at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                 at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

**Comment by MGaetan89** [comment]
Maybe a duplicate of #133?
