### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by JakeWoki** [evrencoskun/TableView#163]
``` Java
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at com.evrencoskun.tableviewsample.tableview.TableViewAdapter.onBindCellViewHolder(TableViewAdapter.java:130)
    at com.evrencoskun.tableview.adapter.recyclerview.CellRowRecyclerViewAdapter.onBindViewHolder(CellRowRecyclerViewAdapter.java:54)
    at com.evrencoskun.tableview.adapter.recyclerview.CellRowRecyclerViewAdapter.onBindViewHolder(CellRowRecyclerViewAdapter.java:32)
    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
    at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
    at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
    at android.support.v7.widget.GapWorker.prefetchInnerRecyclerViewWithDeadline(GapWorker.java:332)
    at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:348)
    at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
    at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
    at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
    at android.os.Handler.handleCallback(Handler.java:808)
    at android.os.Handler.dispatchMessage(Handler.java:101)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7425)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by evrencoskun** [comment]
@JakeWoki 
You are doing wrong at 130. line on TableViewAdapter. Please check the sample app or the [documentation](https://github.com/evrencoskun/TableView#2-create-your-tableviewadapter)

**Comment by JakeWoki** [comment]
this is demo bug
