### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by blackberry2016** [evrencoskun/TableView#203]
```
E/AndroidRuntime:     at com.evrencoskun.tableview.listener.itemclick.AbstractItemClickListener.onInterceptTouchEvent(AbstractItemClickListener.java:79)
        at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2851)
        at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2979)
```

**Comment by MGaetan89** [comment]
Can you provide the full stacktrace?
Which version of the library are you using?

**Comment by MGaetan89** [comment]
Hi @blackberry2016. Do you still have an issue with v0.8.9?
