### ISSUE TITLE
NullPointerException when loading table with empty cell data

### ISSUE THREAD

**Issue by kAliert** [evrencoskun/TableView#26]
Hi!

I encountered following two bugs, when the table has no / empty cell data:

**1.** the table alignment is not correct

![screenshot_1516656046](https://user-images.githubusercontent.com/21302879/35245150-df1c6aac-ffc2-11e7-9ca9-298763bb67f0.png)

**2.** following NullPointerException gets thrown when clicking on columnheader

E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.widget.RecyclerView$ViewHolder com.evrencoskun.tableview.adapter.recyclerview.CellRecyclerView.findViewHolderForAdapterPosition(int)' on a null object reference
                        at com.evrencoskun.tableview.layoutmanager.CellLayoutManager.getVisibleCellViewsByColumnPosition(CellLayoutManager.java:417)
                        at com.evrencoskun.tableview.handler.SelectionHandler.changeVisibleCellViewsBackgroundForColumn(SelectionHandler.java:291)
                        at com.evrencoskun.tableview.handler.SelectionHandler.selectedColumnHeader(SelectionHandler.java:191)
                        at com.evrencoskun.tableview.handler.SelectionHandler.setSelectedColumnPosition(SelectionHandler.java:47)
                        at com.evrencoskun.tableview.listener.itemclick.ColumnHeaderRecyclerViewItemClickListener.clickAction(ColumnHeaderRecyclerViewItemClickListener.java:37)
                        at com.evrencoskun.tableview.listener.itemclick.AbstractItemClickListener.onInterceptTouchEvent(AbstractItemClickListener.java:45)
                        at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2771)
                        at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2899)
                        at android.view.View.dispatchTouchEvent(View.java:11776)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2962)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2643)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
                        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
                        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
                        at android.app.Activity.dispatchTouchEvent(Activity.java:3307)
                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
                        at android.view.View.dispatchPointerEvent(View.java:12015)
                        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4795)
                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4609)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
                    	at android.view.ViewRootImpl$InputStage.onDeliv

**Comment by evrencoskun** [comment]
Hi @kAliert 

Actually it is not what you think. Alignment is correct but, you can't use TableView without empty data. Because, there are some controls that are for calculate column width values of each cell. And This controls assumes each cell has a data to display. 

Therefore, you can not use TableView without the data.

What exactly do you need?

**Comment by kAliert** [comment]
Hi!

Thanks for your reply. Then i will load dummy data if my data is empty. Maybe you can implement this request (loading table with empty data) in a future release. 

Wish you a nice day.

**Comment by evrencoskun** [comment]
I have written down your request. 

Same to you!
