### ISSUE TITLE
OnClick crashes on latest library version

### ISSUE THREAD

**Issue by andob** [evrencoskun/TableView#290]
Hello, I upgraded the library to version ``0.8.9``. Something is wrong with click events. The app crashes each time the user clicks the cell / column / row.

If the user clicks the cell:

```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.evrencoskun.tableview.listener.ITableViewListener.onCellClicked(androidx.recyclerview.widget.RecyclerView$ViewHolder, int, int)' on a null object reference
	at com.evrencoskun.tableview.listener.itemclick.CellRecyclerViewItemClickListener.clickAction(CellRecyclerViewItemClickListener.java:67)
	at com.evrencoskun.tableview.listener.itemclick.AbstractItemClickListener$1.onSingleTapConfirmed(AbstractItemClickListener.java:65)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:316)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

If the user clicks the column:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.recyclerview.widget.RecyclerView$ViewHolder androidx.recyclerview.widget.RecyclerView.findViewHolderForAdapterPosition(int)' on a null object reference
	at com.evrencoskun.tableview.handler.SelectionHandler.changeVisibleCellViewsBackgroundForColumn(SelectionHandler.java:346)
	at com.evrencoskun.tableview.handler.SelectionHandler.selectedColumnHeader(SelectionHandler.java:228)
	at com.evrencoskun.tableview.handler.SelectionHandler.setSelectedColumnPosition(SelectionHandler.java:85)
	at com.evrencoskun.tableview.listener.itemclick.ColumnHeaderRecyclerViewItemClickListener.clickAction(ColumnHeaderRecyclerViewItemClickListener.java:56)
	at com.evrencoskun.tableview.listener.itemclick.AbstractItemClickListener$1.onSingleTapConfirmed(AbstractItemClickListener.java:65)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

**Comment by salman1696** [comment]
its not fixed yet
