### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=15; index=15

### ISSUE THREAD

**Issue by theapache64** [evrencoskun/TableView#30]
When the column number exceeds 15, am getting below given error. Why ? 

` E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.glowsis.glowmetric, PID: 18632
                                                                        java.lang.ArrayIndexOutOfBoundsException: length=15; index=15
                                                                            at com.theah64.retrokit.utils.tableview.holder.CellViewHolder.setCellModel(CellViewHolder.java:31)
                                                                            at com.theah64.retrokit.utils.tableview.BaseTableAdapter.onBindCellViewHolder(BaseTableAdapter.java:52)
                                                                            at com.evrencoskun.tableview.adapter.recyclerview.CellRowRecyclerViewAdapter.onBindViewHolder(CellRowRecyclerViewAdapter.java:48)
                                                                            at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
                                                                            at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                                            at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
                                                                            at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
                                                                            at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
                                                                            at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
                                                                            at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by evrencoskun** [comment]
Hi @theapache64, 

According to the exception, there is something wrong on `setCellModel`method. It tries to do something on non-existent index, It does not say much more.

Could you please share your `CellViewHolder` with me ?

**Comment by theapache64** [comment]
https://gist.github.com/c8b06c4f0cab601493b4f8f98c4b6a7e

**Comment by evrencoskun** [comment]
Hi @theapache64 , 

The reason that you got the exception is being constant of length of `COLUMN_TEXT_ALIGNS`.  In TableView Sample app, I wanted to show that each column could have a different text align. 

As you can see in `ColumnHeaderViewHolder` there is a static constant that store each text alignments of columns. So, each cell should be considered this constant be in alignment with the column.

You can say, Why this constant in this class ? Of course, this is not best practise. 
You can create your own TableView view model that can has all the visual configurations of the TableView such as Text aligns and view types etc. 

```java
public static final int[] COLUMN_TEXT_ALIGNS = {
            // Id
            Gravity.CENTER,
            // Name
            Gravity.LEFT,
            // Nickname
            Gravity.LEFT,
            // Email
            Gravity.LEFT,
            // BirthDay
            Gravity.CENTER,
            // Gender (Sex)
            Gravity.CENTER,
            // Age
            Gravity.CENTER,
            // Job
            Gravity.LEFT,
            // Salary
            Gravity.CENTER,
            // CreatedAt
            Gravity.CENTER,
            // UpdatedAt
            Gravity.CENTER,
            // Address
            Gravity.LEFT,
            // Zip Code
            Gravity.RIGHT,
            // Phone
            Gravity.RIGHT,
            // Fax
            Gravity.RIGHT};
}

```

**Comment by theapache64** [comment]
Ohh.. i got it. bro. Thank you so much for your valuable time
