### ISSUE TITLE
Can't create any cells

### ISSUE THREAD

**Issue by Crightub** [evrencoskun/TableView#66]
With my Code i can create the Corner, Column Header and Row header however I can't create the cells. The onCreateCellViewHolder won't be called. 
My Layouts and Holders are the same as in the sample app.

My Adapter: 
`public class TVAdapterTimetable extends AbstractTableAdapter<ColumnHeader, RowHeader, Cell> {

    public TVAdapterTimetable(Context context) {
        super(context);

    }

    @Override
    public RecyclerView.ViewHolder onCreateCellViewHolder(ViewGroup parent, int viewType) {
        System.out.println("Create Cell View Holder...");

        // Get cell xml layout
        View layout = LayoutInflater.from(mContext).inflate(R.layout.table_view_cell_layout,
                parent, false);

        // Create a Custom ViewHolder for a Cell item.
        return new CellViewHolder(layout);
    }

    @Override
    public void onBindCellViewHolder(AbstractViewHolder holder, Object cellItemModel, int
            columnPosition, int rowPosition) {

        Cell cell = (Cell) cellItemModel;

        System.out.println("Set Attributes for the Cell");

        // Get the holder to update cell item text
        CellViewHolder viewHolder = (CellViewHolder) holder;
        viewHolder.cell_textview.setText(cell.getData().toString());

        // If your TableView should have auto resize for cells & columns.
        // Then you should consider the below lines. Otherwise, you can ignore them.

        // It is necessary to remeasure itself.
        viewHolder.itemView.getLayoutParams().width = LinearLayout.LayoutParams.WRAP_CONTENT;
        viewHolder.cell_textview.requestLayout();
    }

    @Override
    public RecyclerView.ViewHolder onCreateColumnHeaderViewHolder(ViewGroup parent, int viewType) {

        System.out.println("Create ColumnHeader View Holder...");

        // Get Column Header xml Layout
        View layout = LayoutInflater.from(mContext).inflate(R.layout
                .table_view_column_header_layout, parent, false);

        // Create a ColumnHeader ViewHolder
        return new ColumnHeaderViewHolder(layout, getTableView());
    }

    @Override
    public void onBindColumnHeaderViewHolder(AbstractViewHolder holder, Object columnHeaderItemModel, int
            position) {
        ColumnHeader columnHeader = (ColumnHeader) columnHeaderItemModel;

        // Get the holder to update cell item text
        ColumnHeaderViewHolder columnHeaderViewHolder = (ColumnHeaderViewHolder) holder;
        columnHeaderViewHolder.column_header_textview.setText(columnHeader.getData().toString());

        // If your TableView should have auto resize for cells & columns.
        // Then you should consider the below lines. Otherwise, you can ignore them.

        // It is necessary to remeasure itself.
        columnHeaderViewHolder.column_header_container.getLayoutParams().width = LinearLayout
                .LayoutParams.WRAP_CONTENT;
        columnHeaderViewHolder.column_header_textview.requestLayout();
    }

    @Override
    public RecyclerView.ViewHolder onCreateRowHeaderViewHolder(ViewGroup parent, int viewType) {

        // Get Row Header xml Layout
        View layout = LayoutInflater.from(mContext).inflate(R.layout
                .table_view_row_header_layout, parent, false);

        // Create a Row Header ViewHolder
        return new RowHeaderViewHolder(layout);
    }

    @Override
    public void onBindRowHeaderViewHolder(AbstractViewHolder holder, Object rowHeaderItemModel, int
            position) {
        RowHeader rowHeader = (RowHeader) rowHeaderItemModel;

        // Get the holder to update row header item text
        RowHeaderViewHolder rowHeaderViewHolder = (RowHeaderViewHolder) holder;
        rowHeaderViewHolder.row_header_textview.setText(rowHeader.getData().toString());
    }

    @Override
    public View onCreateCornerView() {
        // Get Corner xml layout
        return LayoutInflater.from(mContext).inflate(R.layout.table_view_corner_layout, null);
    }

    @Override
    public int getColumnHeaderItemViewType(int columnPosition) {
        // The unique ID for this type of column header item
        // If you have different items for Cell View by X (Column) position,
        // then you should fill this method to be able create different
        // type of CellViewHolder on "onCreateCellViewHolder"
        return 0;
    }

    @Override
    public int getRowHeaderItemViewType(int rowPosition) {
        // The unique ID for this type of row header item
        // If you have different items for Row Header View by Y (Row) position,
        // then you should fill this method to be able create different
        // type of RowHeaderViewHolder on "onCreateRowHeaderViewHolder"
        return 0;
    }

    @Override
    public int getCellItemViewType(int columnPosition) {
        // The unique ID for this type of cell item
        // If you have different items for Cell View by X (Column) position,
        // then you should fill this method to be able create different
        // type of CellViewHolder on "onCreateCellViewHolder"
        return 0;
    }
}
`

There is no "Create Cell View Holder..." and i always get this message:
02-28 16:34:02.954 2676-2676/de.tk.annapp W/View: requestLayout() improperly called by com.evrencoskun.tableview.adapter.recyclerview.CellRecyclerView{6b3989d VFED..... ......I. 0,98-0,98 #62} during layout: running second layout pass

**Comment by evrencoskun** [comment]
Hi @Crightub,

I don't think this is because of your TableView Adapter. Becuase, there is no any strange thing on your adapter.

Could you please share your initialize code of your TableView? So we can find a clue to be able to find out what exactly made this issue.

See you.

**Comment by Crightub** [comment]
`    Fragment:

public timetableFragment() {
        // Required empty public constructor
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        initData();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle
            savedInstanceState) {
        View root = inflater.inflate(R.layout.fragment_timetable, container, false);

        RelativeLayout fragment_container = root.findViewById(R.id.fragment_container);

        // Create Table view
        mTableView = createTableView();
        fragment_container.addView(mTableView);

        daynames = getResources().getStringArray(R.array.day_names);
        schoolhours = getResources().getStringArray(R.array.school_hours);

        loadData();
        return root;
    }

    private TableView createTableView() {
        TableView tableView = new TableView(getContext());

        // Set adapter
        mTableViewAdapter = new TVAdapterTimetable(getContext());
        tableView.setAdapter(mTableViewAdapter);

        // Set layout params
        FrameLayout.LayoutParams tlp = new FrameLayout.LayoutParams(FrameLayout.LayoutParams
                .MATCH_PARENT, FrameLayout.LayoutParams.MATCH_PARENT);
        tableView.setLayoutParams(tlp);

        // Set TableView listener
        tableView.setTableViewListener(new MyTableViewListener(tableView));
        return tableView;
    }


    private void initData() {
        mRowHeaderList = new ArrayList<>();
        mColumnHeaderList = new ArrayList<>();
        mCellList = new ArrayList<>();
        for (int i = 0; i < ROW_SIZE; i++) {
            mCellList.add(new ArrayList<Cell>());
        }
    }

    private void loadData() {
        List<RowHeader> rowHeaders = getRowHeaderList();
        List<List<Cell>> cellList = getCellListForSortingTest();
        List<ColumnHeader> columnHeaders = getColumnHeaderList(); 

        mRowHeaderList.addAll(rowHeaders);

        for (int i = 0; i < cellList.size(); i++) {
            mCellList.get(i).addAll(cellList.get(i));
        }

        // Load all data
        mColumnHeaderList.addAll(columnHeaders);
        mTableViewAdapter.setAllItems(mColumnHeaderList, mRowHeaderList, mCellList);

    }`

**Comment by evrencoskun** [comment]
I don't see anything that makes this problem.  Is the layout of this fragment same as the sample app? 

If you don't mind, you can share your project with me. So, I can clearly review your code.

**Comment by evrencoskun** [comment]
Hi @Crightub 

If you cell data set is empty, then you can check #62 issue. It may help your problem.

**Comment by Crightub** [comment]
Tableview: 

https://github.com/Crightub/AnnApp/tree/master/app/src/main/java/de/tk/annapp/TableView 

Fragment: 

https://github.com/Crightub/AnnApp/blob/master/app/src/main/java/de/tk/annapp/Fragments/timetableFragment.java

**Comment by evrencoskun** [comment]
Hi, @Crightub 

I have reviewed almost all your code. But I don't see any difference between your codes and the codes of the sample app. 

Which android version did you get this case? 

I have just googled your error and It seems there is a [bug ](https://stackoverflow.com/questions/24598977/android-requestlayout-improperly-called )of Android framework 

Could you please test your case on different a device which has bigger than 5.0 version?

**Comment by 1110101** [comment]
Had a smiliar issue. 

Attach your inflated view to root to fix this:

> Fragment: 
> `    View root = inflater.inflate(R.layout.fragment_timetable, container, **true**);
> ` 

Problem is, `mCellRecyclerView` in `CellLayoutManager` is always null if you don't attach your view to root. Because `onAttachedToWindow()` in `CellLayoutManager:75` won't be called.

**Comment by TxxxxxKXxxxxxxx** [comment]
> Hi, @Crightub
> 
> I have reviewed almost all your code. But I don't see any difference between your codes and the codes of the sample app.
> 
> Which android version did you get this case?
> 
> I have just googled your error and It seems there is a bug of Android framework
> 
> Could you please test your case on different a device which has bigger than 5.0 version?

I've tested it in Android 8.1 so the version could not be the Problem

**Comment by TxxxxxKXxxxxxxx** [comment]
@1110101 
> Had a smiliar issue.
> 
> Attach your inflated view to root to fix this:
> 
> Fragment:
> View root = inflater.inflate(R.layout.fragment_timetable, container, **true**);
> 
> Problem is, mCellRecyclerView in CellLayoutManager is always null if you don't attach your view to root. Because onAttachedToWindow() in CellLayoutManager:75 won't be called.

App crashed after changing to your suggested solution

**Comment by 1110101** [comment]
Can you share a crashreport?

**Comment by TxxxxxKXxxxxxxx** [comment]
@1110101 
`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: de.tk.annapp, PID: 4252
                  java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                      at android.view.ViewGroup.addViewInner(ViewGroup.java:4915)
                      at android.view.ViewGroup.addView(ViewGroup.java:4746)
                      at android.view.ViewGroup.addView(ViewGroup.java:4686)
                      at android.view.ViewGroup.addView(ViewGroup.java:4659)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1281)
                      at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2415)
                      at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2194)
                      at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2148)
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2049)
                      at android.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
`
