### ISSUE TITLE
Preference is causing crash when table is empty

### ISSUE THREAD

**Issue by sonique6784** [evrencoskun/TableView#84]
Hi!

savePreferences() is causing crash when empty, cause not child can be found.

`java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getLeft()' on a null object reference
        at com.evrencoskun.tableview.handler.ScrollHandler.getColumnPositionOffset(ScrollHandler.java:112)
        at com.evrencoskun.tableview.handler.PreferencesHandler.savePreferences(PreferencesHandler.java:43)
        at com.evrencoskun.tableview.TableView.onSaveInstanceState(TableView.java:730)`

**Comment by evrencoskun** [comment]
Hi @sonique6784 

Thanks for the bug report.
