### ISSUE TITLE
How do i unselect a CellViewHolder? 

### ISSUE THREAD

**Issue by tuvirus** [evrencoskun/TableView#94]
I'm trying to unselect the cell from the table, aslo it should unselect the colum and row headers. How can i accomplish that?

Plus: I'm deleting a row that is charged with SQlite Data. I'm trying to refresh my tableview with the changes i made. But nothing happends. And doing it throught a PopUpMenu as used in OnLongPressedColumnView.

**Comment by evrencoskun** [comment]
Hi @tuvirus,

To clear selections, use the below code;

`tableView.getSelectionHandler().clearSelection();`

TableViewAdapter has two methods to remove the desired row easily. These are;
- removeRow(int rowPosition); 
- removeRow(int rowPosition, boolean updateRowHeader) ; 

you can easily row the row like this;

`tableView.getAdapter().removeRow(rowPosition);
`

**Comment by tuvirus** [comment]
Thanks about the removeRow method, helped me a lot :D . But the clearSelection(); method does not exists :(. 

Good day!

**Comment by evrencoskun** [comment]
0.8.7 and 0.8.8 which is the newest version has the method.

**Comment by SnehaInGitHub** [comment]
If I want to delete multiple rows at a single shot, any method available for that?

**Comment by evrencoskun** [comment]
Hi @SnehaInGitHub 

You can remove multiple rows using these; 
- `removeRowRange(int rowPositionStart, int itemCount)`
- `removeRowRange(int rowPositionStart, int itemCount, boolean updateRowHeader)`

**Comment by SnehaInGitHub** [comment]
@evrencoskun 
I want to delete multiple rows that are not contiguous in manner. A user can select multiple rows at a time and can delete all selected rows. I tried to use `removeRow` method of yours. But as inside the removeRow method, you have -
` mCellRecyclerViewAdapter.deleteItem(rowPosition);
        mRowHeaderRecyclerViewAdapter.deleteItem(rowPosition);`

Now `deleteItem` method has notifyItemRemoved method. So, I am getting an arrayIndexOutOfBound exception.

**Comment by tuvirus** [comment]
@evrencoskun ,
Hello, thanks for the reply, it worked it unselects, but check on this. I'm using tabs in my app, one of the tabs has de the TableView while i'm on the tab i can unselect but on scrolling, because my table is a bit long, seems like the not rendered cells are still selected and also when i go on another tab and comeback to the TableView Tab it reselects itself again (Row/column/cell) from the last selection i've made. I think it is some kind of bug(?).

Here some screenshots:
![screenshot_20180717-104821](https://user-images.githubusercontent.com/35820047/42829568-75fdf1c2-89af-11e8-8d3f-5df5ce6fca6a.png)
![screenshot_20180717-104757](https://user-images.githubusercontent.com/35820047/42829569-761fe7be-89af-11e8-8e14-c9a4d5b96d49.png)

**Comment by djdance** [comment]
And I can't clear selection. What should I do?

> java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.widget.RecyclerView$ViewHolder com.evrencoskun.tableview.adapter.recyclerview.CellRecyclerView.findViewHolderForAdapterPosition(int)' on a null object reference
>                                                         at com.evrencoskun.tableview.handler.SelectionHandler.changeVisibleCellViewsBackgroundForColumn(SelectionHandler.java:342)
>                                                         at com.evrencoskun.tableview.handler.SelectionHandler.unselectedColumnHeader(SelectionHandler.java:234)
>                                                         at com.evrencoskun.tableview.handler.SelectionHandler.clearSelection(SelectionHandler.java:407)

**Comment by DescodeNet** [comment]
SelectionHandler in clearSelection() Method : 
unselectedRowHeader();
unselectedCellView();
unselectedColumnHeader();

add:

        mPreviousSelectedViewHolder = null;
        mSelectedColumnPosition = UNSELECTED_POSITION;
        mSelectedRowPosition = UNSELECTED_POSITION;
`

**Comment by Jhon354202** [comment]
> 嗨@tuvirus，
> 
> 要清除选择，请使用以下代码；
> 
> `tableView.getSelectionHandler().clearSelection();`
> 
> TableViewAdapter有两种方法可以轻松删除所需的行。这些是;
> 
> * removeRow（int rowPosition）;
> * removeRow（int rowPosition，boolean updateRowHeader）;
> 
> 您可以像这样轻松地排行；
> 
> `tableView.getAdapter().removeRow(rowPosition); `

Tableview. Getselectionhandler(). Clearselection(); but how to solve the null pointer exception?

**Comment by ShrutiGhime** [comment]
Hey, I am using date range picker so I just want to select those rows under that range of date 

Please help 
![Screenshot_20210422-171839](https://user-images.githubusercontent.com/74654547/115728775-69ccf000-a3a2-11eb-8e8b-183d31026e13.jpg)
